version: '3.1'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - '9999:9999'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass